<section class="homePage">
    <article>
        <h2>You realy want to delete your account?</h2>
        <div id='questions'>
            <img src="css/images/avatar.png" alt="bee">
            <button>yes</button>
            <a href="index.php"><button>No, just kidding</button></a>
        </div>
    </article>
    <form id='deleteAccount' action="" method="post">    
        <label for="email">Please enter your email and your password </label>
        <span id='message'></span>
        <input type="email" name="email"  placeholder="enter your mail" required>
        <input type="password" name="password"  placeholder='enter your password' required>
        <button>delete</button>
    </form>
</section> 