<section class="homePage">  
    <form action="" method="post">    
        <label for="email">Please enter your email and new password </label>
        <span id='message'></span>
        <input type="email" name="email"  placeholder="enter your mail" required>
        <input type="password" name="password"  placeholder='enter your password' required>
        <a href="home">GO Home</a>
        <button>send</button>
    </form>
</section> 