<section id='post'>
    <article>
        <h2>Write your five gratitudes of the day</h2>
        <img src="css/images/avatar.png" alt="">
        <form action="" method="post">
            <span></span>
            <textarea name="post" maxlength='250'  rows="10" placeholder="250 characters max,  use coma to separate your gratitudes"></textarea>
            <button type="submit">POST</button>
        </form>
    </article>
    <article>
        <a href="log_out">log out</a>
        <a href="landing_page">home</a>
    </article>   
</section>